Repository jetstack/vault-helper, pull requests merged in 2018-06, with the labels that each got.

#20 Adds EnsureDryRun, Delete and versioning
  .gitignore
  Makefile
  main.go
  pkg/kubernetes/certificate_test.go
  pkg/kubernetes/generic.go
  pkg/kubernetes/generic_test.go
  pkg/kubernetes/init_token.go
  pkg/kubernetes/init_token_test.go
  pkg/kubernetes/kubernetes.go
  pkg/kubernetes/kubernetes_fake_test.go
  pkg/kubernetes/kubernetes_mocks_test.go
  pkg/kubernetes/kubernetes_pki_roles.go
  pkg/kubernetes/kubernetes_policies.go
  pkg/kubernetes/kubernetes_test.go
  pkg/kubernetes/pki.go
  pkg/kubernetes/pki_test.go
  pkg/testing/api/api_test.go
  pkg/testing/api/delete_test.go
  pkg/testing/api/dry_run_test.go
  pkg/testing/cli/cli_test.go
  pkg/testing/vault_dev/vault_dev.go
Labels: approved, lgtm, release-note, size/XXL

#25 Migrate docker_* build targets to use docker cp
  Makefile
Labels: approved, lgtm, release-note, size/M

#23 Write the encryption config to vault
  pkg/kubernetes/generic.go
  pkg/kubernetes/kubernetes_policies.go
Labels: approved, lgtm, release-note, size/M

#24 Rename vault backends
  pkg/kubernetes/generic_vault_backend.go
  pkg/kubernetes/generic_vault_backend_test.go
  pkg/kubernetes/init_token.go
  pkg/kubernetes/init_token_test.go
  pkg/kubernetes/kubernetes.go
  pkg/kubernetes/kubernetes_pki_roles.go
  pkg/kubernetes/kubernetes_policies.go
  pkg/kubernetes/kubernetes_test.go
  pkg/kubernetes/pki_vault_backend.go
  pkg/kubernetes/pki_vault_backend_test.go
  pkg/testing/api/delete_test.go
  pkg/testing/api/dry_run_test.go
Labels: approved, lgtm, release-note-none, size/L

#26 Add 0.9.11 release note
  CHANGELOG.md
Labels: approved, lgtm, release-note-none, retest-not-required-docs-only, size/S

#27 Encrypt configmaps
  CHANGELOG.md
  pkg/kubernetes/generic_vault_backend.go
Labels: approved, lgtm, release-note, size/XS
