Repository jetstack/vault-helper, pull requests merged in 2018-04, with the labels that each got.

#14 Enable prow builds
  .gitlab-ci.yml
  Makefile
  labels.yaml
Labels: approved, lgtm, release-note, size/L

#11 Merge cert and kubeconfig flags + ensure args are parsed before running
  cmd/cert.go
  cmd/kubeconfig.go
  pkg/cert/cert.go
  pkg/kubeconfig/kubeconfig.go
  pkg/kubeconfig/kubeconfig_test.go
  pkg/kubeconfig/kubeconfig_yaml.go
Labels: approved, lgtm, release-note, size/L

#15 Enable client flag on kube-apiserver cert
  pkg/kubernetes/kubernetes_pki_roles.go
Labels: approved, lgtm, release-note

#18 Adds "*.ec2.internal" common_name for kubelet role
  pkg/kubernetes/certificate_test.go
  pkg/kubernetes/kubernetes_pki_roles.go
Labels: approved, lgtm, release-note, size/M

#16 Jetstack Copyright headers
  Dockerfile
  Gopkg.lock
  Gopkg.toml
  Makefile
  cmd/cert.go
  cmd/dev_server.go
  cmd/init.go
  cmd/kubeconfig.go
  cmd/read.go
  cmd/setup.go
  cmd/token_renew.go
  cmd/version.go
  hack/boilerplate/boilerplate.Dockerfile.txt
  hack/boilerplate/boilerplate.Makefile.txt
  hack/boilerplate/boilerplate.go.txt
  hack/boilerplate/boilerplate.py
  hack/boilerplate/boilerplate.py.txt
  hack/boilerplate/boilerplate.sh.txt
  hack/boilerplate/boilerplate_test.py
  hack/boilerplate/test/fail.go
  hack/boilerplate/test/fail.py
  hack/boilerplate/test/pass.go
  hack/boilerplate/test/pass.py
  hack/verify-boilerplate.sh
  main.go
  pkg/cert/cert.go
  pkg/cert/cert_CSR.go
  pkg/cert/cert_ensure.go
  pkg/cert/cert_test.go
  pkg/dev_server/dev_server.go
  pkg/instanceToken/instance_token.go
  pkg/instanceToken/renew_token.go
  pkg/instanceToken/renew_token_test.go
  pkg/kubeconfig/kubeconfig.go
  pkg/kubeconfig/kubeconfig_test.go
  pkg/kubeconfig/kubeconfig_yaml.go
  pkg/kubernetes/certificate_test.go
  pkg/kubernetes/generic.go
  pkg/kubernetes/generic_test.go
  pkg/kubernetes/init_token.go
  pkg/kubernetes/init_token_test.go
  pkg/kubernetes/kubernetes.go
  pkg/kubernetes/kubernetes_fake_test.go
  pkg/kubernetes/kubernetes_mocks_test.go
  pkg/kubernetes/kubernetes_pki_roles.go
  pkg/kubernetes/kubernetes_policies.go
  pkg/kubernetes/kubernetes_test.go
  pkg/kubernetes/pki.go
  pkg/kubernetes/pki_test.go
  pkg/kubernetes/policy.go
  pkg/read/read.go
  pkg/testing/cli/cert_test.go
  pkg/testing/cli/cli_test.go
  pkg/testing/cli/kubeconfig_test.go
  pkg/testing/cli/read_test.go
  pkg/testing/cli/token_renew_test.go
  pkg/testing/vault_dev/vault_dev.go
Labels: approved, lgtm, release-note-none, size/L
