Repository jetstack/vault-helper, pull requests merged in 2019-01, with the labels that each got.

#34 Upgrade vault to 0.9.6
  .gitlab-ci.yml
  CHANGELOG.md
  Dockerfile
  Gopkg.lock
  Gopkg.toml
  Makefile
  pkg/cert/cert_ensure.go
  vendor/github.com/golang/mock/gomock/call.go
  vendor/github.com/golang/mock/gomock/callset.go
  vendor/github.com/golang/mock/gomock/controller.go
  vendor/github.com/golang/mock/mockgen/mockgen.go
  vendor/github.com/golang/mock/mockgen/model/model.go
  vendor/github.com/golang/mock/mockgen/parse.go
  vendor/github.com/golang/mock/mockgen/reflect.go
  vendor/github.com/hashicorp/vault/api/logical.go
  vendor/github.com/hashicorp/vault/api/renewer.go
  vendor/github.com/hashicorp/vault/api/sys_auth.go
  vendor/github.com/hashicorp/vault/api/sys_mounts.go
  vendor/github.com/hashicorp/vault/helper/compressutil/compress.go
  vendor/github.com/hashicorp/vault/helper/jsonutil/json.go
  vendor/github.com/hashicorp/vault/helper/strutil/strutil.go
  vendor/github.com/spf13/cobra/cobra/cmd/license_agpl.go
  vendor/github.com/spf13/cobra/cobra/cmd/license_apache_2.go
  vendor/github.com/spf13/cobra/cobra/cmd/license_bsd_clause_2.go
  vendor/github.com/spf13/cobra/cobra/cmd/license_bsd_clause_3.go
  vendor/github.com/spf13/cobra/cobra/cmd/license_gpl_2.go
  vendor/github.com/spf13/cobra/cobra/cmd/license_gpl_3.go
  vendor/github.com/spf13/cobra/cobra/cmd/license_lgpl.go
  vendor/github.com/spf13/cobra/cobra/cmd/license_mit.go
  vendor/github.com/spf13/cobra/cobra/cmd/licenses.go
  vendor/golang.org/x/net/context/context.go
  vendor/golang.org/x/net/context/go17.go
  vendor/golang.org/x/net/context/go19.go
  vendor/golang.org/x/net/context/pre_go17.go
  vendor/golang.org/x/net/context/pre_go19.go
Labels: approved, lgtm, release-note, size/XXL

#30 Fix typo in log/error output
  pkg/kubernetes/generic_vault_backend.go
Labels: approved, lgtm, release-note-none, size/XS

#35 Upgrade golang to 1.11.4
  .gitlab-ci.yml
  CHANGELOG.md
  Makefile
Labels: approved, lgtm, release-note, size/XS

#36 Use DOCKER_HOST: tcp://localhost:2375
  .gitlab-ci.yml
Labels: approved, lgtm, release-note, size/XS

#38 Upgrades alpine image to 3.8
  Dockerfile
Labels: approved, lgtm, release-note, size/XS

#39 Use Debian stretch image in gitlab CI
  .gitlab-ci.yml
Labels: approved, lgtm, release-note, size/XS
